export default {
    ON_LOGIN_SUCCESS: "ON_LOGIN_SUCCESS",
    ON_LOGIN_FAIL: "ON_LOGIN_FAIL",
    ON_LOGOUT_SUCCESS: "ON_LOGOUT_SUCCESS",
    ON_CHANGE_PROFILE:"ON_CHANGE_PROFILE",
    ON_CHANGE_QUANTITY_CART: "ON_CHANGE_QUANTITY_CART"
};
